### ISSUE TITLE
unicorn-store - `Deployment failed: Error: Failed to publish asset`

### ISSUE THREAD

**Issue by mafulafunk** [awsdocs/aws-lambda-developer-guide#442]
in:

```
./labs/unicorn-store
```

executing:

› ./setup-infrastructure.sh

runs into an error, what am I missing?

```
[...]
 ⏳  Bootstrapping environment aws://523030116397/eu-central-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.

 ✨ hotswap deployment skipped - no changes were detected (use --force to override)

 ✅  Environment aws://523030116397/eu-central-1 bootstrapped (no changes).


✨  Synthesis time: 9.38s

UnicornStoreInfrastructure:  start: Building 3849c2cabbaf014495bc1109885e72ab0a52584cf1d9a86b75f393a78ac7bf97:current_account-current_region
UnicornStoreInfrastructure:  success: Built 3849c2cabbaf014495bc1109885e72ab0a52584cf1d9a86b75f393a78ac7bf97:current_account-current_region
UnicornStoreInfrastructure:  start: Building 70a53f05cc412ec7e6a24242cdf63e063465d1ae6d3a10773218338ed7b90e51:current_account-current_region
UnicornStoreInfrastructure:  success: Built 70a53f05cc412ec7e6a24242cdf63e063465d1ae6d3a10773218338ed7b90e51:current_account-current_region
UnicornStoreInfrastructure:  start: Publishing 3849c2cabbaf014495bc1109885e72ab0a52584cf1d9a86b75f393a78ac7bf97:current_account-current_region
UnicornStoreInfrastructure:  start: Publishing 70a53f05cc412ec7e6a24242cdf63e063465d1ae6d3a10773218338ed7b90e51:current_account-current_region
UnicornStoreInfrastructure:  fail: No bucket named 'cdk-hnb659fds-assets-523030116397-eu-central-1'. Is account 523030116397 bootstrapped?
UnicornStoreInfrastructure:  fail: No bucket named 'cdk-hnb659fds-assets-523030116397-eu-central-1'. Is account 523030116397 bootstrapped?

 ❌ Deployment failed: Error: Failed to publish asset 3849c2cabbaf014495bc1109885e72ab0a52584cf1d9a86b75f393a78ac7bf97:current_account-current_region
    at Deployments.publishSingleAsset (/usr/local/lib/node_modules/aws-cdk/lib/index.js:415:11819)
    at async Object.publishAsset (/usr/local/lib/node_modules/aws-cdk/lib/index.js:415:151100)
    at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:415:137075

Failed to publish asset 3849c2cabbaf014495bc1109885e72ab0a52584cf1d9a86b75f393a78ac7bf97:current_account-current_region
cat: target/output.json: No such file or directory

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: the following arguments are required: outfile

```

**Comment by mwunderl** [comment]
Hi Martin, is this feedback for https://github.com/aws-samples/aws-lambda-java-workshop ?
